import AddIcon from '@mui/icons-material/Add';
import AdjustIcon from '@mui/icons-material/Adjust';
import DriveFileRenameOutlineIcon from '@mui/icons-material/DriveFileRenameOutline';
import KeyboardDoubleArrowRightIcon from '@mui/icons-material/KeyboardDoubleArrowRight';
import MarkEmailUnreadIcon from '@mui/icons-material/MarkEmailUnread';
import SettingsIcon from '@mui/icons-material/Settings';
import StarHalfIcon from '@mui/icons-material/StarHalf';
import SupervisorAccountIcon from '@mui/icons-material/SupervisorAccount';

export const config = [
  {
    labelType: 'text',
    labelText: 'OverView',
    labelIcon: MarkEmailUnreadIcon,
    labelInfo: '',
    color: '#3c8039',
    bgColor: '#e6f4ea',
    nodeId: '1',
  },
  {
    labelType: 'text',
    labelText: 'Users',
    labelIcon: StarHalfIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '2',
  },
  {
    labelType: 'text',
    labelText: 'Proposals',
    labelIcon: DriveFileRenameOutlineIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '3',
  },

  {
    labelType: 'text',
    labelText: 'Setting',
    labelIcon: SettingsIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '4',
  },
  {
    labelType: 'box',
    labelText: 'Projects',
    labelIcon: SupervisorAccountIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '5',
  },
  {
    labelType: 'text',
    labelText: 'Targets',
    labelIcon: KeyboardDoubleArrowRightIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '6',
  },
  {
    labelType: 'text',
    labelText: 'Activity',
    labelIcon: KeyboardDoubleArrowRightIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '7',
  },
  {
    labelType: 'text',
    labelText: 'Timeline',
    labelIcon: KeyboardDoubleArrowRightIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '8',
  },
  {
    labelType: 'text',
    labelText: 'subDAO',
    labelIcon: AddIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '9',
  },
  {
    labelType: 'box',
    labelText: 'Assets',
    labelIcon: SupervisorAccountIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '10',
  },
  {
    labelType: 'text',
    labelText: 'NFts',
    labelIcon: AdjustIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '11',
  },
  {
    labelType: 'text',
    labelText: 'Budget',
    labelIcon: AdjustIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '12',
  },
  {
    labelType: 'box',
    labelText: 'Community',
    labelIcon: AdjustIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '13',
  },
  {
    labelType: 'text',
    labelText: 'Chat',
    labelIcon: AdjustIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '14',
  },
  {
    labelType: 'text',
    labelText: 'NIP',
    labelIcon: AdjustIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '15',
  },
  {
    labelType: 'text',
    labelText: 'Suggestions',
    labelIcon: AdjustIcon,
    labelInfo: '',
    color: '#1a73e8',
    bgColor: '#F3F6F9',
    nodeId: '16',
  },
];
